# Generated by Django 4.0.5 on 2022-07-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinfo_city_alter_userinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.CharField(default='', max_length=12, null=True, verbose_name='ZIP/ Postal code'),
        ),
    ]
