# Generated by Django 4.0.5 on 2022-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_state_alter_userinfo_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='medicationnurse',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address_1',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address_2',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='workstationnurse',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
    ]
