# Generated by Django 4.0.5 on 2022-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctor_full_name_alter_manager_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-device_id']},
        ),
    ]
