# Generated by Django 4.0.5 on 2022-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_patient_has_covid_alter_patient_has_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Insurance Company'),
        ),
    ]
