# Generated by Django 4.0.5 on 2022-07-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patient_insurance_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='has_Diabetes',
            new_name='has_diabetes',
        ),
    ]
