# Generated by Django 4.0.5 on 2022-06-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, null=True, verbose_name='Medication Name')),
                ('med_freq', models.CharField(max_length=200, null=True, verbose_name='Frequency')),
                ('med_amount', models.CharField(max_length=200, null=True, verbose_name='Amount')),
                ('med_strength', models.CharField(max_length=200, null=True, verbose_name='Strength')),
                ('med_route', models.CharField(max_length=200, null=True, verbose_name='Route')),
                ('med_refills', models.CharField(max_length=200, null=True, verbose_name='Refills')),
                ('med_dispense', models.CharField(max_length=200, null=True, verbose_name='Dispense')),
                ('med_time', models.TimeField(null=True, verbose_name='Time')),
                ('med_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('med_end_date', models.DateField(null=True, verbose_name='End Date')),
                ('m_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.medicationnurse')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('w_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workstationnurse')),
            ],
        ),
        migrations.CreateModel(
            name='HoursOfMedicationNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(verbose_name='Date')),
                ('total_hours', models.CharField(max_length=30, null=True, verbose_name='Total Hours')),
                ('m_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.medicationnurse')),
            ],
            options={
                'ordering': ['-day_date'],
            },
        ),
    ]
