# Generated by Django 4.0.5 on 2022-07-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HR', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Heart Rate')),
                ('spo2', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='SPO2')),
                ('temp', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Temperature')),
                ('sys_pressure', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Systolic Pressure')),
                ('dia_pressure', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Diastolic Pressure')),
                ('date_in', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('time_in', models.TimeField(auto_now_add=True, null=True, verbose_name='Time')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'ordering': ['-date_in'],
            },
        ),
    ]
