# Generated by Django 4.0.5 on 2022-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_nurse', '0005_alter_tasklist_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='is_done',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Done'),
        ),
    ]
