# Generated by Django 4.0.5 on 2022-06-29 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('time_in', models.TimeField(auto_now_add=True, null=True, verbose_name='Time')),
                ('comment', models.TextField(max_length=3000, null=True, verbose_name='Comments')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to='accounts.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
