# Generated by Django 4.0.5 on 2022-07-07 14:55

from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_device_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to='accounts.userinfo'),
        ),
    ]
