# Generated by Django 4.0.5 on 2022-07-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_has_diabetes_patient_has_diabetes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='has_Covid',
            new_name='has_covid',
        ),
    ]
