# Generated by Django 4.0.5 on 2022-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Room Name'),
        ),
    ]
