# Generated by Django 4.0.5 on 2022-07-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to='chatapp.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to=settings.AUTH_USER_MODEL),
        ),
    ]
