# Generated by Django 4.0.5 on 2022-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='full_name',
            field=models.CharField(default='', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
