# Generated by Django 4.0.5 on 2022-07-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patient_user_info'),
        ('medication_nurse', '0002_alter_medication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['med_time']},
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('delivery_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Time')),
                ('m_nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.medicationnurse')),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medication_nurse.medication')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
            options={
                'ordering': ['delivery_date'],
            },
        ),
    ]
