# Generated by Django 4.0.5 on 2022-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication_nurse', '0003_alter_medication_options_tasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='delivery_date',
            field=models.DateField(default='', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='delivery_time',
            field=models.TimeField(default='', null=True, verbose_name='Time'),
        ),
    ]
