# Generated by Django 4.0.5 on 2022-07-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientparameter',
            name='env_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Environment Temperature'),
        ),
        migrations.AlterField(
            model_name='patientparameter',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Body Temperature'),
        ),
    ]
